### PR TITLE
Added spanish translation

### PR DESCRIPTION
**Pull request by obelisk-services**
Including app.js translation (used for calendar mainly)

### CODE REVIEW

**Comment by holema** [comment]
Man, thats so great. we will merge it instantly.

We use crowdin to do the translations, but I will import it there and then crowdin will push it to the repo

**Review by holema — APPROVED** [review]

**Comment by obelisk-services** [comment]
Sorry, I didn't know you use Crowdin. Anyway, I realized there are some missing texts in the file I uploaded (we downloaded it like 2 months ago and woked on it, but meanwhile you commited a new version with more texts). Once you have imported all our translations in crowdin we will translate the remaining ones. Hope it helps the project :)

**Comment by holema** [comment]
@obelisk-services 
I added your translation to the crowdin Project
https://crowdin.com/project/jitsi-admin

It would be so great when you translate it directly in crowdin. Then it is pushed directly into the repo.

**Comment by obelisk-services** [comment]
Yes, we'll translate it directly in crowdin next time :)

**Comment by obelisk-services** [comment]
I think it's fully translated now :)
If you need more spanish translations in the future, don't hesitate to contact us :)

**Pull request merged**
